version: "2"

networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    networks:
      - app-tier
  kafka:
    image: "bitnami/kafka:latest"
    networks:
      - app-tier
  game-events-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=development
      - POSTGRES_USER=development
