// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.2
// source: create-game-event.proto

package tutorialpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GameEventServiceClient is the client API for GameEventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameEventServiceClient interface {
	CreateGameEvent(ctx context.Context, in *NewGameEvent, opts ...grpc.CallOption) (*NewGameEventCreated, error)
}

type gameEventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameEventServiceClient(cc grpc.ClientConnInterface) GameEventServiceClient {
	return &gameEventServiceClient{cc}
}

func (c *gameEventServiceClient) CreateGameEvent(ctx context.Context, in *NewGameEvent, opts ...grpc.CallOption) (*NewGameEventCreated, error) {
	out := new(NewGameEventCreated)
	err := c.cc.Invoke(ctx, "/board_game.GameEventService/CreateGameEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameEventServiceServer is the server API for GameEventService service.
// All implementations must embed UnimplementedGameEventServiceServer
// for forward compatibility
type GameEventServiceServer interface {
	CreateGameEvent(context.Context, *NewGameEvent) (*NewGameEventCreated, error)
	mustEmbedUnimplementedGameEventServiceServer()
}

// UnimplementedGameEventServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGameEventServiceServer struct {
}

func (UnimplementedGameEventServiceServer) CreateGameEvent(context.Context, *NewGameEvent) (*NewGameEventCreated, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGameEvent not implemented")
}
func (UnimplementedGameEventServiceServer) mustEmbedUnimplementedGameEventServiceServer() {}

// UnsafeGameEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameEventServiceServer will
// result in compilation errors.
type UnsafeGameEventServiceServer interface {
	mustEmbedUnimplementedGameEventServiceServer()
}

func RegisterGameEventServiceServer(s grpc.ServiceRegistrar, srv GameEventServiceServer) {
	s.RegisterService(&GameEventService_ServiceDesc, srv)
}

func _GameEventService_CreateGameEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewGameEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameEventServiceServer).CreateGameEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/board_game.GameEventService/CreateGameEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameEventServiceServer).CreateGameEvent(ctx, req.(*NewGameEvent))
	}
	return interceptor(ctx, in, info, handler)
}

// GameEventService_ServiceDesc is the grpc.ServiceDesc for GameEventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameEventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "board_game.GameEventService",
	HandlerType: (*GameEventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGameEvent",
			Handler:    _GameEventService_CreateGameEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "create-game-event.proto",
}
