apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: infra
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      name: mongo
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
        - image: mongo:6.0.4
          name: mongo
          # securityContext:
          #   privileged: true
          resources:
            requests:
              memory: "4000Mi"
              cpu: "2000m"
            limits:
              memory: "4000Mi"
              cpu: "2000m"
          ports:
            - name: mongo
              containerPort: 27017
              hostPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          # persistentVolumeClaim:
          #   claimName: mongo-storage-claim
